include:
  - package:flutter_lints/flutter.yaml
  - package:bloc_lint/recommended.yaml
  
formatter: 
  page_width: 110


linter:
  rules:
    camel_case_types: true
    constant_identifier_names: true
    file_names: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    prefer_single_quotes: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_string_escapes: true
    unnecessary_this: true
    valid_regexps: true
    # Flutter specific lints
    use_super_parameters: true
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_const_constructors_in_immutables: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
    avoid_dynamic_calls: true
    avoid_annotating_with_dynamic: true
    exhaustive_cases: true
    only_throw_errors: true
    prefer_final_locals: true
    unnecessary_async: true
    await_only_futures: true
    avoid_void_async: true
    always_put_required_named_parameters_first: true

analyzer:
  exclude:
    - build/**
  errors:
    missing_override_of_must_be_overridden: error
    inference_failure_on_function_invocation: ignore
    await_only_futures: warning
    avoid_void_async: warning
    avoid_dynamic_calls: error
    return_without_value: error
