name: system_loja
description: Sistema de gerenciamento de loja com Flutter
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.10.3"

dependencies:
  log_custom_printer:
    git:
      url: https://github.com/saulogatti/log_custom_printer.git
      ref: uopdateLib
  flutter:
    sdk: flutter

  path_provider: ^2.1.5
  synchronized: ^3.4.0
  path: ^1.9.1
  json_annotation: ^4.9.0
  
  async: ^2.13.0
  meta: ^1.17.0
  crypto: ^3.0.7
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  freezed_annotation: ^3.1.0
  freezed: ^3.2.4
  bloc_lint: ^0.3.6
  equatable: ^2.0.8
  plugin_platform_interface: ^2.1.8
  path_provider_platform_interface: ^2.1.2

  auto_route: ^11.1.0
  intl: ^0.20.2
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  sqlite3_flutter_libs: ^0.5.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  json_serializable: ^6.11.4
  drift_dev: ^2.30.1
flutter:
  uses-material-design: true
